# Generated by Django 3.1.7 on 2021-03-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardId', models.CharField(max_length=256)),
                ('replywriter', models.CharField(max_length=256)),
                ('replycontent', models.TextField()),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'boardreply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('userpassword', models.CharField(max_length=256)),
                ('usermail', models.CharField(max_length=256)),
                ('regDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Webboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('regDate', models.DateTimeField(auto_now_add=True)),
                ('replycount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'webboard',
                'managed': False,
            },
        ),
    ]
