# Generated by Django 3.1.7 on 2021-03-16 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardtext',
            options={'managed': False},
        ),
    ]
