# Generated by Django 3.1.7 on 2021-03-25 05:26

import boardapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardId', models.CharField(max_length=256)),
                ('upload_files', models.FileField(blank=True, null=True, upload_to=boardapp.models.get_file_path, verbose_name='添付ファイル')),
                ('filename', models.CharField(max_length=100, null=True, verbose_name='ファイル名')),
            ],
        ),
    ]
