# Generated by Django 3.1.7 on 2021-03-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20210316_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('regDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webboard',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BoardText',
        ),
    ]
