# Generated by Django 3.1.7 on 2021-03-23 08:40

import boardapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_boardreply_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardId', models.CharField(max_length=64, null=True,  verbose_name='boardId')),
                ('upload_files', models.FileField(blank=True, null=True, upload_to=boardapp.models.get_file_path, verbose_name='파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
            ],
        ),
    ]
