# Generated by Django 3.1.7 on 2021-03-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_testfileupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testfileupload',
            options={'managed': False},
        ),
    ]
