# Generated by Django 3.1.7 on 2021-03-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0006_auto_20210324_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testfileupload',
            options={},
        ),
    ]
